### ISSUE TITLE
[Export] Export custom fields `number_in_sequence` and `original_citation` as additional_descriptions

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1022]
Realistically, custom fields won't be ready for initial launch. In a migration meeting, we decided to export `number_in_sequence` and `original_citation` via additional descriptions.

Here is the approach (comment below to discuss it!):

Export the corresponding DH fields as Prism `additional_descriptions` items.

| DH field                                                          | Prism				 |
| ----------------------------------------------------------------- | ------------------ |
| `page_number` or `page_number_actual` (probably not `page_count`) | number_in_sequence |
| `bibliographic_citation` 											| original_citation  |

DH fields are to be double-checked if they are the right ones.

The added additional_description item will look like:

```json
    {
      "description": "number_in_sequence: <value>",
      "type": {
        "id": "other"
      }
    },
```
AND/OR

```json
    {
      "description": "original_citation: <value>",
      "type": {
        "id": "other"
      }
    }
```

For example, for a DH record with `page_number` of value `3` and `bibliographic_citation` of value `Custom original citation` and no other `additional_descriptions`, the export for `additional_descriptions` will look like:

```json
"additional_descriptions": [
  {
    "description": "number_in_sequence: 3",
    "type": {
      "id": "other"
    }
  },
  {
    "description": "original_citation: Custom original citation",
    "type": {
      "id": "other"
    }
  }
]
```

**Comment by Meowcenary** [comment]
From what I've found `page_number` and `page_number_actual` are the same, but `page_number` is stored as a string and `page_number_actual` as an integer. There are a few cases where `page_number` will be something like "13a" while `page_number_actual` is `nil`. Searching through the codebase it seems like `page_number_actual` uses integers because of a Solr query in the catalog controller (line 59 in `app/controllers/catalog_controller.rb`). With this in mind I'm going to map `page_number` to `number_in_sequence` even though the name `page_number_actual` seems more authoritative
