### ISSUE TITLE
Investigate what publication date is sent for DOI minting on DH

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1026]
Investigate what publication date is sent for DOI minting on DH so that we know if we need to re-assess which field needs to be used in the export.

**Comment by gneidhardt** [comment]
Below is documentation from DataCite. Note that in order to implement their recommendation (publication date = date of digitization/availability of digital object; with original creation date in title) would take significant data remediation on our part. I think our question is do we continue our local practice, which has largely been to consider publication date as date of creation of work; or do we switch going forward and implement DataCite standards? 

Note that @kglibrarian is also asking IR managers listserv and might have future input.

https://schema.datacite.org/meta/kernel-4.4/doc/DataCite-MetadataKernel_v4.4.pdf (page 18)

In the case of a digitised version of a physical object
If the DOI is being used to identify a digitised version of an original item, the recommended approach is
to supply the PublicationYear for the digital version and not the original object.
The Title field may be used to convey the approximate or known date of the original object. Other
metadata properties available for additional date information about the object include: Subject and
Description. However, only Title will be part of the citation.
Here are two examples of citations using dates or date information in the titles.
Schmidt, S., Andersen, V., Belviso, S., & Marty, J.-C. (2002). Dissolved and particulate thorium 234
concentration at time series station DYFAMED from date 1995-05-07 (Data set). PANGAEA - Data
Publisher for Earth & Environmental Science. https://doi.org/10.1594/pangaea.183607
Tape, K. D. (2015). Aerial Images of Alaska’s Arctic Coastal Plain; 1948-1949. U.S. Geological Survey.
(Image). https://doi.org/10.5066/f79021tb

**Comment by sharpattack** [comment]
@fenekku @gneidhardt @kglibrarian The `publicationDate` sent to Datacite for DOI is only the YEAR of the date of UPLOAD.

**Comment by fenekku** [comment]
:open_mouth: ... Prism uses the year of the publication date metadata field. So we should expect to see that difference percolate up. 

Thanks @sharpattack .

**Comment by fenekku** [comment]
@gneidhardt @kglibrarian I am closing this since Austin provided us with the info. This is something important to know about Prism and Datacite going forward.
