### ISSUE TITLE
[Export/Import] Geographic subject terms

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1032]
Those were placed in `"metadata.locations.features": [{"place": <here>}]` on Prism, but it makes more sense to place them in `metadata.subjects` under a vocabulary.

We need to see what vocabulary was used on DH for this field. Can we re-use it in Prism? If yes export to this field.
e.g., if it's LCNAF, then we can export to LCNAF

According to https://github.com/galterlibrary/digital-repository/issues/1033#issuecomment-1169107264, the vocabulary used in DH was a subset of LCNAF (only heading and only direct geographic locations)

**Comment by Meowcenary** [comment]
LCNAF lookups are taking a really long time because the file is 840mb compared to 54mb and 72mb for the other subject files. I'm not sure how to make it smaller, but maybe there's a way to look things up faster?

**Comment by Meowcenary** [comment]
A few things to try to speed this up:

- I'm modifying an existing script to build a cache of LCNAF terms so that it uses the most up to date fields (GenericFile#subject_geographic, GenericFile#subject_name)
- Not a huge change, but using jsonl instead of csv for the searchable headers file format
- Adding a cache for terms that we know do not exist. This can be passed on to librarians for review and will save time on future exports
