### ISSUE TITLE
[Export] Update LCSH/MeSH terms lookup  

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1036]
Analysis on Prism of missed LCSH / MeSH terms:

MeSH terms (with qualifier replacement - see below)
Found 982 valid terms out of 1144 missed terms

LCSH terms
Found 274 valid terms out of 318 missed terms

[lcsh_analysis.csv](https://github.com/galterlibrary/digital-repository/files/9003971/lcsh_analysis.csv)
[mesh_analysis.csv](https://github.com/galterlibrary/digital-repository/files/9003972/mesh_analysis.csv)

Task is to update the lookup code to:

- use the [subjects_mesh.jsonl](https://github.com/galterlibrary/invenio-subjects-mesh/blob/master/invenio_subjects_mesh/vocabularies/subjects_mesh.jsonl) and [subjects_lcsh.jsonl](https://github.com/galterlibrary/invenio-subjects-lcsh/blob/master/invenio_subjects_lcsh/vocabularies/subjects_lcsh.jsonl) as source of lookup
- make sure to perform qualifier replacement (i.e. replace "--" by "/") for **MeSH terms only**
- don't bother going out to the network

The unfound terms after this are minimal and I think we can ignore them.

**Comment by Meowcenary** [comment]
I might make a PR to update the lookup files to jsonl to help speed up DigitalHub. It's consistently very slow to initialize because of the header lookup :(

**Comment by Meowcenary** [comment]
Sorry for the label stuff - wanted to add these as a workaround for estimating tickets with points.

**Comment by Meowcenary** [comment]
This went surprisingly well! Testing on staging to see if there are memory improvements

**Comment by gneidhardt** [comment]
I finished going through the LCSH terms, and all are fixed (or ignored, in the case of trailing spaces), except for the following, which originally read as FALSE. These are all valid/TRUE LCSH terms and should be added to our internal validation list:

- Bibliographical citations--Computer programs	TRUE-add to list
- Clinical trials--Moral and ethical aspects	TRUE-add to list
- Dental schools--history	TRUE-add to list
- Physicians--Selection and appointment	TRUE-add to list
- Resumes (Employment)	TRUE-add to list (DigitalHub doesn't like diacritics, which is why I guess this one is failing. If I add the diacritics in DH, the letters are erased (so this would read Rsums (Employment))
- Scholarly communication	TRUE-add to list

Still working on MeSH - hope to have those in the next few days.

**Comment by fenekku** [comment]
@gneidhardt thanks for editing the LCSH terms on DH. So I understand correctly:

1. In most False cases, you either removed the LCSH term from the record or replaced it with a correct one?

2. You didn't remove the extra ending whitespace for LCSH terms that had one, right? This would make sense because we can deal with this. @Meowcenary this may have to be added to the export script.

3. How did you validate that those remaining terms are indeed valid? From looking at a May 6th dump of LCSH terms and the website I get:

**variant**
"Scholarly communication" is a variant of "Communication in learning and scholarship" Its id is http://id.loc.gov/authorities/subjects/sh97005983 .

In general we don't support variants as potential values - too much data not enough resources yet. We only support their main form for now. Can we change the term on DH? otherwise @Meowcenary has to convert on export.

**simply cannot find**
Bibliographical citations--Computer programs
Physicians--Selection and appointment
Dental schools--history
Clinical trials--Moral and ethical aspects

Those are not part of the official dump. Nor can I find them on the LCSH website (e.g., https://id.loc.gov/search/?q=Bibliographical+citations--Computer+programs&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fauthorities%2Fsubjects
) Where are they coming from? what would their id be?

**Comment by gneidhardt** [comment]
1. In most False cases, you either removed the LCSH term from the record or replaced it with a correct one? **Yes**
2. You didn't remove the extra ending whitespace for LCSH terms that had one, right? This would make sense because we can deal with this. @Meowcenary this may have to be added to the export script. **Correct**
3. **Notes below in bold**

variant
"Scholarly communication" is a variant of "Communication in learning and scholarship" Its id is http://id.loc.gov/authorities/subjects/sh97005983 . **I did go ahead and change this one (apologies - there's a publication called "Scholarly communication" that was misleading**

simply cannot find

- Bibliographical citations--Computer programs **(no good substitute found - here is the general subdivision record for Computer programs: https://id.loc.gov/authorities/subjects/sh99005296.html)**
- Physicians--Selection and appointment **(no good substitute found - here is the general subdivision record for Selection and appointments: https://id.loc.gov/authorities/subjects/sh99002537.html)**
- Dental schools--history **(removed - duplicated in MeSH)**
- Clinical trials--Moral and ethical aspects **(removed - duplicated in MeSH)**

**These are all valid complex subject headings, with approved subdivisions appearing after the "--". Sometimes these complex headings are so common that LCSH indexes them as their own official headings with their own ID numbers (example: https://id.loc.gov/authorities/subjects/sh2010115722.html), but the vast majority are constructed by catalogers as we need them.  I went ahead and deleted the second two since they were duplicated in MeSH, but unless we have a stricter rule in Prism than we do in DigitalHub, librarian submitters will likely still add ones like this since they'd be considered valid in a library catalog environment. Unfortunately, unlike in MeSH, LCSH doesn't just concatenate the main heading and subdivision IDs to form an ID for the complex subject, so if we do need an ID for the first two, I'm not sure what to suggest here, but I'm open to ideas.**

**Comment by fenekku** [comment]
:hammer: on the nail: "we do need an id for the first two" . That's what we need.  

Now the flip-side is that librarians wouldn't be able to add these qualifiers for LCSH given they are not part of the imported LCSH vocaublary :laughing: . The difficulty is that we need all these unique permutations pre-stored...

**Comment by gneidhardt** [comment]
Thought instead of adding a new ticket (though I can do that if you want) I'd comment here to say that Resumes (Employment) is still an issue (see https://vtfsmghslrepo02.fsm.northwestern.edu/records/myw89-yf437 and https://digitalhub.northwestern.edu/files/a8ea36c6-a95f-4de2-ab7c-e5e15df46484). I'm guessing LCSH Resumes (Employment) didn't migrate from DH because it's missing its diacritics in DH (they don't display). Would the solution here be to add this to items that should have this in Prism as the actual LCSH text ("Résumés (Employment)")? This would affect 57 records, which is possible manually, but if there is a way to do it automatically that would be great. 

Here's the full list for my reference: https://digitalhub.northwestern.edu/catalog?f%5Btags_sim%5D%5B%5D=Resumes+%28Employment%29&q=%22resumes+%28employment%29%22

**Comment by fenekku** [comment]
Thanks for spotting that! I made a ticket out of it: https://github.com/galterlibrary/digital-repository/issues/1087 . Pretty sure we should be able to fix this without @gneidhardt  needing to change anything.
