### ISSUE TITLE
De-duplicate DOIs

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#1049]
On DH, there are 3 cases of duplicate DOIs. InvenioRDM doesn't allow 2 different records to have the same DOI in accordance with DOI rules, so when trying to migrate these records we get errors.

**DOI: 10.18131/g3-syas-dv10**
Records sharing it:
    - https://digitalhub.northwestern.edu/files/a31212fc-f486-4ad8-85fc-d8c03ac94c11 (Biostats 101: The Minor Details that Make a Major Difference)
    - https://digitalhub.northwestern.edu/files/162523bb-47e9-4734-9d75-f9cd59661a58 (Biostatistics Collaboration at Northwestern: Finding Your Way to A Friendly Statistician)
DOI resolution: https://digitalhub.northwestern.edu/files/162523bb-47e9-4734-9d75-f9cd59661a58
Conclusion: https://digitalhub.northwestern.edu/files/a31212fc-f486-4ad8-85fc-d8c03ac94c11 needs a different DOI.

**DOI: 10.15844/pedneurbriefs-2-9-10**
Records sharing it:
    - https://digitalhub.northwestern.edu/files/pnb-2-9-72 (Language Development and Otitis Media)
    - https://digitalhub.northwestern.edu/files/pnb-2-9-71 (Sucrose, Motor Activity, and Learning)
DOI resolution: https://www.pediatricneurologybriefs.com/article/10.15844/pedneurbriefs-2-9-10/ (Sucrose, Motor Activity, and Learning)
Conclusion: https://digitalhub.northwestern.edu/files/pnb-2-9-72 needs a different DOI. I actually couldn't find the "Language Development and Otitis Media" article on https://www.pediatricneurologybriefs.com but maybe you will have better luck than me.

**DOI: 10.21985/n2-vsb2-cm32**
Records sharing it:
    - https://digitalhub.northwestern.edu/files/1a167f1c-bf07-402c-9662-0c09e5c57721 (Supplementary_tables.xlsx)
    - https://digitalhub.northwestern.edu/files/5fc602e7-b0d1-4e5d-9da6-a4556f410d7e (Enhancer Malfunction Underlies Transcriptional Dysregulation in Uterine Leiomyoma.pdf)
DOI resolution: https://arch.library.northwestern.edu/concern/generic_works/tq57nr288 (Enhancer Malfunction Underlies Transcriptional Dysregulation in Uterine Leiomyoma.pdf)
Conclusion: https://digitalhub.northwestern.edu/files/1a167f1c-bf07-402c-9662-0c09e5c57721 needs a different DOI.

For the needed different DOIs, hopefully there is one that is already existing. If no appropriate one can be found, Prism can mint a new DOI for the record on migration.

**Comment by gneidhardt** [comment]
I also want to page @kglibrarian, since she's got much more background on these items and DOIs. My thoughts are below.

For 1 (Conclusion: https://digitalhub.northwestern.edu/files/a31212fc-f486-4ad8-85fc-d8c03ac94c11 needs a different DOI) I agree. I don't see that one exists, but want to check with @kglibrarian before minting a new one.

For 2 (Conclusion: https://digitalhub.northwestern.edu/files/pnb-2-9-72 needs a different DOI. I actually couldn't find the "Language Development and Otitis Media" article on https://www.pediatricneurologybriefs.com/ but maybe you will have better luck than me.) I am very confused - this is just one page of a PDF that doesn't look like other PNB items, and the title looks like it's a summary of an article from another journal (J Speech and Hearing Disorders Aug 1988) when you open the file. @kglibrarian, any thoughts here? Do we want to keep this in our system at all, or rename and re-DOI?

For 3 (Conclusion: https://digitalhub.northwestern.edu/files/1a167f1c-bf07-402c-9662-0c09e5c57721 needs a different DOI) I agree. I don't see that one exists, but want to check with @kglibrarian before minting a new one.

**Comment by kglibrarian** [comment]
**For 1: Mint a new DOI.** I agree all of your comments. Let me know how minting a new works. I would imagine deleting the old DOI and re-saving the record, but I don't want to jump to conclusions.  I am happy to do that if I have guessed correctly on the process. 
**For 2: Getting more information.** I have reached out to Dr. Millichap because the DOIs were assigned by PNB. If Dr. Millichap doesn't respond in the timeframe we need (which I am unsure of what that would be), then perhaps we can revert the record to a "Draft" in Prism so that we do not have to assign a DOI and the metadata is not sent to DataCite, but we would have the option to publish it down the road, if needed. If we can't "revert it" then perhaps we can look into not migrating it and uploading it again into Prism as unpublished. Hopefully Dr. Millichap will come through with the correct DOI. 
**For 3: Mint a new DOI.** Likely the depositor wanted to associate their dissertation with their supplementary tables. Since the dissertation is in Arch and there doesn't appear to be an option to upload multiple files for one record in Arch, then I agree, a new DOI should be minted for the supplementary tables. Let me know how that works.  I am happy to do that if I have guessed correctly on the process.

**Comment by fenekku** [comment]
@kglibrarian For minting a DOI on Prism, importing a record without DOI will automatically mint one. @sharpattack For minting on DH, how would it work? 

If we want a DOI sooner rather than later, doing it on DH would be best.

**Comment by sharpattack** [comment]
@fenekku and @kglibrarian Yes, that seems right. As long as there is only one DOI there, just delete it and hit save. DH should automatically create a new one.

**Comment by kglibrarian** [comment]
Updates: 

For 1: A new DOI was minted and note added to "Private Note" field: https://doi.org/10.18131/g3-4vpg-v684

For 2: Dr John Millichap responded and created a new DOI for the item. The DOI has been added to the record and a note was made in the "Private Note" field. 

Record in DH: https://digitalhub.northwestern.edu/files/pnb-2-9-72
DOI: http://doi.org/10.15844/pedneurbriefs-2-9-11

For 3: A new DOI was minted and a note added to the "Private Note" field: https://doi.org/10.18131/g3-qezy-ed71

**Comment by fenekku** [comment]
After verification in export/import, those have indeed been solved. Closing.
