### ISSUE TITLE
GV Black item issues 

### ISSUE THREAD

**Issue by gneidhardt** [galterlibrary/digital-repository#1100]
I assume the issues in this document might be found in other GV Black material (especially for one page items). I assume issues come from combining archival items, but this item is titled "...combined" even though it's a 1:1 item match for its DH counterpart; should be part of GV Black papers or subset, but no collection in Prism; DOI is completely; and ARK is present in Prism but not DH:
- https://digitalhub.northwestern.edu/files/7c298e55-bf15-4435-a625-943da8322274
- https://vtfsmghslrepo02.fsm.northwestern.edu/records/wd100-mv020

In another GV Black set of items, the date created is less specific in Prism than in DH; ARK is present in Prism but not DH; no collection in Prism:
- https://digitalhub.northwestern.edu/files/5h73pw137
- https://vtfsmghslrepo02.fsm.northwestern.edu/records/hg1vf-nws30

Another GV Black set of issues - ARK is present in Prism but not DH; no collection in Prism (should be part of GV Black); original identifier present in DH but not Prism:
- https://digitalhub.northwestern.edu/files/c247ds096
- https://vtfsmghslrepo02.fsm.northwestern.edu/records/zja7n-1ch12

And rounding it out with some extra weird GV Black behavior. For this one, I corrected a MeSH term in DH (was a previous version of term that is no longer valid), but I'm unsure if this will be imported next time, or if this one might be weird since it's a GV Black item; LCNAF name in DH didn't transfer to Prism (front or back end); format is wrong (holdover from system-generated data in DH (jpeg listed instead of tiff, which is the actual file format):
- https://digitalhub.northwestern.edu/files/hq37vn595
- https://vtfsmghslrepo02.fsm.northwestern.edu/records/41r2w-ay161

**Comment by gneidhardt** [comment]
Adding @kglibrarian to review above information - it looks like the files that were migrated perhaps weren't the files intended for migration, so I hesitate to edit the "-combined" files listed above in DH if those aren't the ones that are meant for migration.

**Comment by Meowcenary** [comment]
- After the latest import is ran by @fenekku , follow up with @gneidhardt to ensure that none of the records listed in this ticket still have issues
- If there are lingering issues open a new ticket to specify what is going wrong with those particular records

**Comment by fenekku** [comment]
From 2022-10-20 export/import:

| Title | Digitalhub | Prism | Status |
| ----- | ---------- | ----- | ------ |
| The World's Columbian Dental Congress to be held in Chicago, August 14th to 19th inclusive, 1893 | https://digitalhub.northwestern.edu/files/7c298e55-bf15-4435-a625-943da8322274 | https://vtfsmghslrepo02.fsm.northwestern.edu/records/q08q8-v3k84 | MeSH terms miscategorized |
| World's Columbian Dental Congress member's ticket - Page 2 | https://digitalhub.northwestern.edu/files/5h73pw137 |  | Not exported |
| Drawings on the Cicada, the seventeen year locust - Page 4 | https://digitalhub.northwestern.edu/files/c247ds096 |  | Not exported |
| The World's Columbian Dental Congress to be held in Chicago, August 14th to 19th inclusive, 1893 - Combined | https://digitalhub.northwestern.edu/files/zp38wc71g |https://vtfsmghslrepo02.fsm.northwestern.edu/records/c3vx1-4hp67 | MeSH terms miscategorized |
| World's Columbian Dental Congress member's ticket - Combined |https://digitalhub.northwestern.edu/files/qn59q399p |https://vtfsmghslrepo02.fsm.northwestern.edu/records/qgvx5-qzk87 | MeSH terms miscategorized |
| Drawings on the Cicada, the seventeen year locust - Combined | https://digitalhub.northwestern.edu/files/xg94hp54d | https://vtfsmghslrepo02.fsm.northwestern.edu/records/gn27g-3ks16 | MeSH terms miscategorized |
| G.V. Black as a teacher | https://digitalhub.northwestern.edu/files/hq37vn595 | https://vtfsmghslrepo02.fsm.northwestern.edu/records/6fdpf-vd083 | MeSH terms miscategorized |


MeSH terms miscategorized: [this original problem + fix](https://github.com/galterlibrary/digitalhub-2/issues/293#issuecomment-1258610820) was not backported to v9 yet. I will do so (if it is reviewed in a timely manner) and it should fix it.

**Comment by Meowcenary** [comment]
For the bottom four records in the table Guillaume put together (thanks for that!) it was totally my fault that they exported. A fix
was introduced to not export a specific subtype of file, but I had forgotten to remove an old export folder so they were still
included in the export I sent out. To fix this I have added a line to remove the old export automatically whenever it is run.

The top most record in the table is exporting because the logic we currently have in place is that any file that is in this collection
https://digitalhub.northwestern.edu/collections/x633f100h or a sub-collection of it will not be exported. It turns out that this file
is actually underneath this collection: https://digitalhub.northwestern.edu/collections/a4de96c9-7c6d-40d6-ad9e-cac8a24faad5 which was the one we had previously been marking as the collection not to export.
I'm not sure what the best approach is from here. Maybe we need to hardcode this so that we don't export that file?

**Comment by kglibrarian** [comment]
I think the questions are related to what should be migrated from DigitalHub to Prism? Apologies if I'm missing something. 

Record 1 in the list should be migrated because it is part of the new G.V. Black Collection. 

- The World's Columbian Dental Congress to be held in Chicago, August 14th to 19th inclusive, 1893| https://digitalhub.northwestern.edu/files/7c298e55-bf15-4435-a625-943da8322274

Records 2 & 3 in the list would not be migrated because they are part of the old G.V. Black Collection. 

- World's Columbian Dental Congress member's ticket - Page 2 | https://digitalhub.northwestern.edu/files/5h73pw137
- Drawings on the Cicada, the seventeen year locust - Page 4 | https://digitalhub.northwestern.edu/files/c247ds096

Records 4 through 7 were addressed by Austin, they were part of an old export folder.

**Comment by Meowcenary** [comment]
@kglibrarian no need to apologize. I think _I'm_ the person who is consistently the most confused.

> Record 1 in the list should be migrated because it is part of the new G.V. Black Collection.
> The World's Columbian Dental Congress to be held in Chicago, August 14th to 19th inclusive, 1893| https://digitalhub.northwestern.edu/files/7c298e55-bf15-4435-a625-943da8322274

Okay, that answers my question then. I will submit the PR that removes the old exported files automatically and we can leave this open for review until after the next export / import cycle.

**Comment by sharpattack** [comment]
I will be that guy too: 
- I thought record 7 should be exported, it is part of **_both_** old and new GV Black collections. 
- Any record ending with "- Combined" should not be exported.

**Comment by kglibrarian** [comment]
Ok, I thought it was Austin who said that it was an old export folder, but it was Eric. I didn't check records 4-7 because of Eric's comment, but I looked at them now.  

Record 7: Should be exported
- G.V. Black as a teacher | https://digitalhub.northwestern.edu/files/hq37vn595

Can someone clarify - for the other records -  are the rules saying they shouldn't be exported? They aren't part of the G.V. Black collection, so I had assumed they WOULD be exported. 

Record 4: 
- The World's Columbian Dental Congress to be held in Chicago, August 14th to 19th inclusive, 1893 - Combined | https://digitalhub.northwestern.edu/files/zp38wc71g

Record 5: 
- World's Columbian Dental Congress member's ticket - Combined | https://digitalhub.northwestern.edu/files/qn59q399p

Record 6: 
- Drawings on the Cicada, the seventeen year locust - Combined | https://digitalhub.northwestern.edu/files/xg94hp54d
