### ISSUE TITLE
"Sort by" under catalog needs to have a different default

### ISSUE THREAD

**Issue by vioil** [galterlibrary/digital-repository#168]
As is now the default is relevance even if you don't have a search term entered. 
This is weird I think :bulb:
How about making the *Sort by date uploaded* a default?
![relevance](https://cloud.githubusercontent.com/assets/3239996/9741747/bfabdb28-5621-11e5-8f22-c37daeba970b.jpg)

**Comment by phebal** [comment]
Catalog is sorted by solr score (relevance) and date uploaded in descending order. Score should be one of the default criteria because when someone searches they most likely want the results sorted by relevance. Date sort should also probably stay in a descending order, otherwise we'll show the oldest items first and I don't think that's what we want. In the screenshot above, page 2 shows up above page 1 because it was uploaded later. I'm closing this, please re-open with comments if appropriate.
