### ISSUE TITLE
box access

### ISSUE THREAD

**Issue by vioil** [galterlibrary/digital-repository#478]
Looks like once we give permission to Box to access our box folders it accesses everything, even the folders we are not the owners. I for example have access to Box folders owned by some other universities due to some collaborative work. How do we prevent this?

See screenshot:

<img width="590" alt="boxaccess" src="https://cloud.githubusercontent.com/assets/3239996/18553648/d3f3162a-7b26-11e6-8dfe-229c0a825ee4.png">

**Comment by phebal** [comment]
It'll list anything you have permissions to view. This way you can upload files others shared with you. It's this way by design. It's up to you to not upload things you don't want to upload. All this happens in YOUR browser and not on the server. It's no different than opening box website in your browser really.

**Comment by vioil** [comment]
Please remember this was brought up during the SE roundtable discussion as a concern.
