### ISSUE TITLE
citation date

### ISSUE THREAD

**Issue by vioil** [galterlibrary/digital-repository#503]
Something is off with the dates generated for the citations since it's not picking up the year.
Example:
http://dx.doi.org/10.18131/G3T021
The date is 10/20/2016. 
The citation: 

MLA
Gutzman, Karen E, et al. Digitalhub Poster. **1020**. doi:10.18131/G3T021 

APA
Gutzman, K.E., Ilik, V., Kubilius, R.K., Holmes, K.L., Wishnetsky, S.J., Pastva, J.M., Olson, A.J., Shank, J.P., Hebal, P., & Stirnaman, J.T.T. **(1020)**. DigitalHub Poster. . doi:10.18131/G3T021 

Chicago
Gutzman, Karen E, Violeta Ilik, Ramune Karolina Kubilius, Kristi Lee Holmes, Susan J Wishnetsky, Joelen Michelle Pastva, Anton J Olson, Jonathan P Shank, Piotr Hebal, and Jason T Todd Stirnaman. Digitalhub Poster. **1020**. doi:10.18131/G3T021

**Comment by phebal** [comment]
This is happening because Date Created is improperly filled out. From the description:
>The date on which the content was created, produced or published. Dates are accepted in the form YYYY-MM-DD, e.g. 1976-07-04.

What's in the field though is `10/20/2016' and the software doesn't know how to parse this. It expects the first 4 numbers to represent the year, hence `1020`. Solution here is to adhere to the recommended date format. If we don't then the software has to guess. Imagine a date of `5/1/2016`. Is it May 1st or January 5th?

**Comment by vioil** [comment]
I realized that last night and forgot to tell you. I will fix the date in that item. nothing for you to do now. thanks
