### ISSUE TITLE
Create list of netid, email, fullname from owners of records

### ISSUE THREAD

**Issue by fenekku** [galterlibrary/digital-repository#753]

**Comment by Meowcenary** [comment]
This seems relatively simple. Here is the script we are currently considering:

```
require 'csv'

CSV.open("dh_file_owners.csv", "w") do
  csv << ["File Id", "Owner Net Id", "Owner Email", "Owner Fullname"]
  GenericFile.all.each do |gf|
    user = User.find_by(username: gf.depositor)
    csv << [gf.id, user.username, user.email, user.name]
  end
end
```

**Comment by Meowcenary** [comment]
Find collections or files that have been deposited on behalf of another user. See how these files store "depositor" in the database.

**Comment by Meowcenary** [comment]
I've attached the CSV I generated with the script that is currently under review. If there are revisions that result in a change to this I'll edit this comment. Because GitHub does not support `.csv` files I used `.txt` instead, so you will have to rename this to `dh_file_owners.csv` after downloading.

[dh_file_owners.txt](https://github.com/galterlibrary/digital-repository/files/6173959/dh_file_owners.txt)
